app-template:
  controllers:
    main:
      containers:
        main:
          env:
            ALLOWED_ORIGINS: '["https://cdn-explorer.ducal.me"]'
            DEBUG: 'false'
            DEMO_MODE: 'false'
          image:
            repository: ghcr.io/chrysa/cdn-explorer
            tag: v0.1.0
          probes:
            liveness:
              custom: true
              enabled: true
              spec:
                failureThreshold: 3
                httpGet:
                  path: /health
                  port: 8000
                initialDelaySeconds: 15
                periodSeconds: 30
            readiness:
              custom: true
              enabled: true
              spec:
                httpGet:
                  path: /health
                  port: 8000
                initialDelaySeconds: 10
                periodSeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            runAsNonRoot: true
  ingress:
    main:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        gethomepage.dev/description: CDN crawler API
        gethomepage.dev/enabled: 'true'
        gethomepage.dev/group: Dev
        gethomepage.dev/icon: sh-chrysa
        gethomepage.dev/name: CDN Explorer API
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.middlewares: infra-tinyauth-auth@kubernetescrd,infra-security-headers@kubernetescrd
      className: traefik
      hosts:
      - host: cdn-explorer-api.ducal.me
        paths:
        - path: /
          pathType: Prefix
          service:
            identifier: main
            port: http
      tls:
      - hosts:
        - cdn-explorer-api.ducal.me
        secretName: cdn-explorer-api-tls
  service:
    main:
      controller: main
      ports:
        http:
          port: 8000
