updates:
- directory: /
  labels:
  - dependencies
  package-ecosystem: pip
  schedule:
    interval: weekly
- directory: /app
  labels:
  - dependencies
  package-ecosystem: npm
  schedule:
    interval: weekly
- directory: /
  labels:
  - dependencies
  package-ecosystem: docker
  schedule:
    interval: weekly
version: 2
