services:
  api:
    build:
      context: .
      target: dev
    environment:
      ALLOWED_ORIGINS: '["http://localhost:5173","http://localhost:8011"]'
      DEBUG: 'true'
    ports:
    - 8010:8000
    volumes:
    - ./api:/app/api:ro
  app:
    build:
      context: ./app
      target: dev
    environment:
      VITE_API_URL: ''
    ports:
    - 5173:5173
    volumes:
    - ./app/src:/app/src:ro
