on:
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
  push:
    branches:
    - develop
    - main
    - master
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  sonar:
    if: github.actor != 'dependabot[bot]'
    name: SonarCloud scan
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - name: SonarCloud scan
      uses: chrysa/github-actions/sonar-scan@v1
      with:
        project-key: chrysa_cdn-explorer
        sonar-token: ${{ secrets.SONAR_TOKEN }}
        sources: .
        tests: tests
    timeout-minutes: 15
name: SonarCloud Analysis
permissions:
  contents: read
  pull-requests: read
